apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{doris.clusterName}}-doris-be
  labels:
    app: {{doris.clusterName}}-doris-be
spec:
  replicas: {{doris.dorisBeConfig.replicas}}
  volumeClaimTemplates:
    - metadata:
        name: pvc-doris-be
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
  serviceName: doris-be-headless
  selector:
    matchLabels:
      app: {{doris.clusterName}}-doris-be
  template:
    metadata:
      labels:
        app: {{doris.clusterName}}-doris-be
    spec:
      nodeSelector:
        <%
        for(entry in doris.dorisBeConfig.nodeSelectors){
        %>
        "{{entry.key}}": "{{entry.value}}"
        <% } %>
      volumes:
        - name: doris-script
          configMap:
            name: {{doris.clusterName}}-doris-script-configmap
            defaultMode: 0744
        - name: doris-conf
          configMap:
            name: {{doris.clusterName}}-doris-configmap
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: doris-be
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: "Asia/Shanghai"
            - name: BE_IPADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: {{doris.dorisBeConfig.dockerImage}}
          imagePullPolicy: Always
          command: [ "/bin/bash", "-ce", "/opt/script/be_bootstrap.sh  " ]
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{doris.dorisBeConfig.webserverPort}}
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: {{doris.dorisBeConfig.bePort}}
              protocol: TCP
            - containerPort: 9070
              protocol: TCP
            - containerPort: {{doris.dorisBeConfig.webserverPort}}
              protocol: TCP
            - containerPort: {{doris.dorisBeConfig.heartBeatPort}}
              protocol: TCP
            - containerPort: {{doris.dorisBeConfig.brpcPort}}
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2G
            requests:
              cpu: 200m
              memory: 1G
          volumeMounts:
            - name: pvc-doris-be
              mountPath: /opt/doris/be/storage
            - name: doris-conf
              mountPath: /opt/doris/be/conf/be.conf
              subPath: be.conf
            - name: doris-script
              mountPath: /opt/register_be.sh
              subPath: register_be.sh
            - name: doris-script
              mountPath: /opt/script

