kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{doris.clusterName}}-doris-fe
  labels:
    app: {{doris.clusterName}}-doris-fe
spec:
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: pvc-doris-fe
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
  serviceName: doris-fe-headless
  selector:
    matchLabels:
      app: {{doris.clusterName}}-doris-fe
  template:
    metadata:
      labels:
        app: {{doris.clusterName}}-doris-fe
    spec:
      volumes:
        - name: doris-conf
          configMap:
            name: {{doris.clusterName}}-doris-configmap
        - name: doris-script
          configMap:
              name: {{doris.clusterName}}-doris-script-configmap
              defaultMode: 0744
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
      <%
      for(entry in doris.dorisFeConfig.nodeSelectors){
      %>
        "{{entry.key}}" : "{{entry.value}}"
      <% } %>
      
      
      containers:
        - name: doris-fe
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: FE_IPADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: {{doris.dorisFeConfig.dockerImage}}
          imagePullPolicy: Always
          command: [ "/bin/bash", "-ce", "/opt/script/fe_bootstrap.sh" ]
          volumeMounts:
            - name: pvc-doris-fe
              mountPath: /opt/doris/fe/doris-meta
            - name: doris-conf
              mountPath: /opt/doris/fe/conf/fe.conf
              subPath: fe.conf
            - name: doris-script
              mountPath: /opt/script
          livenessProbe:
            httpGet:
              path: /api/bootstrap
              port: {{doris.dorisFeConfig.httpPort}}
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: {{doris.dorisFeConfig.httpPort}}
              protocol: TCP
            - containerPort: {{doris.dorisFeConfig.rpcPort}}
              protocol: TCP
            - containerPort: {{doris.dorisFeConfig.queryPort}}
              protocol: TCP
            - containerPort: {{doris.dorisFeConfig.editLogPort}}
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 4G
            requests:
              cpu: 200m
              memory: 1G